build_from:
  aarch64: alpine:3.20
  amd64: alpine:3.20
  armv7: alpine:3.20
labels:
  org.opencontainers.image.title: RTL-TCP (RTL-SDR Blog driver)
  org.opencontainers.image.source: https://github.com/BrawnyBravo/ha-sdr-addon
